version = 0.1
[default.deploy.parameters]
stack_name = "kasama-lambda-test"
resolve_s3 = true
s3_prefix = "kasama-lambda-test"
region = "ap-northeast-1"
profile = "infa-role"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
