---
AWSTemplateFormatVersion: "2010-09-09"
Description:  S3 Bucket
Resources:
  CmKasamaPracticeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cm-kasama-practice
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true