AWSTemplateFormatVersion: "2010-09-09"
Description: Create IAM-Role for same region replication of  S3 log bucket
Parameters:
  Env:
    Type: String
    AllowedValues: 
      - dev
      - prod
    Default: dev
Resources:
  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      # RoleName: Assume-${Env}-Replicate-Role
      RoleName: Assume-dev-Replicate-Role
      Policies:
        - PolicyName: data-log-allow-get-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:Get*
                Resource:
                  - !Sub arn:aws:s3:::kasama-${Env}-log
                  - !Sub arn:aws:s3:::kasama-${Env}-log/*
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                  - s3:GetObjectVersionTagging
                Resource:
                  - !Sub arn:aws:s3:::kasama-${Env}-log-replicate
                  - !Sub arn:aws:s3:::kasama-${Env}-log-replicate/*
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: s3.amazonaws.com
            Action:
              - "sts:AssumeRole"
Outputs:
  RoleARN:
    Value: !GetAtt IAMRole.Arn
    Export:
      Name: !Sub Assume-${Env}-Replicate-Role
  RoleId:
    Value: !GetAtt IAMRole.RoleId
    Export:
      Name: !Sub Assume-${Env}-Replicate-Id