AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secret Manager for Salesforce tokens with AppFlow permissions'

Parameters:
  SalesforceAccessToken:
    Type: String
    NoEcho: true
    Description: 'Salesforce Access Token'

  SalesforceRefreshToken:
    Type: String
    NoEcho: true
    Description: 'Salesforce Refresh Token'

Resources:
  SalesforceTokensSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: '/salesforce/dev/appflow-cm-kasama-sf-connector-credentials'
      Description: 'Salesforce Access and Refresh Tokens'
      SecretString: 
        !Sub |
          {
            "accessToken": "${SalesforceAccessToken}",
            "refreshToken": "${SalesforceRefreshToken}"
          }

  SalesforceTokensSecretPolicy:
    Type: 'AWS::SecretsManager::ResourcePolicy'
    Properties:
      SecretId: !Ref SalesforceTokensSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appflow.amazonaws.com
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:PutSecretValue
              - secretsmanager:DeleteSecret
              - secretsmanager:DescribeSecret
              - secretsmanager:UpdateSecret
            Resource: '*'
